import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateDb1711504331985 implements MigrationInterface {
    name = 'CreateDb1711504331985'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`faculties\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`form_file\` (\`id\` int NOT NULL AUTO_INCREMENT, \`link\` varchar(255) NOT NULL, \`serviceId\` int NULL, \`departmentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`officer_roles_role\` (\`officerId\` int NOT NULL, \`roleId\` int NOT NULL, INDEX \`IDX_1d723096d5579f576d8269deba\` (\`officerId\`), INDEX \`IDX_8cba317f8029863fb8ced75517\` (\`roleId\`), PRIMARY KEY (\`officerId\`, \`roleId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`phone\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`in_class\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`address\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`gender\` enum ('male', 'female') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`avatar\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`facultyId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`officer\` ADD \`phone\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`officer\` ADD \`address\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`officer\` ADD \`gender\` enum ('male', 'female') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`officer\` ADD \`avatar\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`label\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`routerLink\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`icon\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`parent_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`nav_menu\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`attribute_form_enum\` DROP FOREIGN KEY \`FK_db6f5036fca0a8ff7b66e43d85a\``);
        await queryRunner.query(`ALTER TABLE \`attribute_form_enum\` CHANGE \`attributeFormServiceId\` \`attributeFormServiceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` DROP FOREIGN KEY \`FK_da748edb0d12d7b468002ef37f6\``);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` DROP FOREIGN KEY \`FK_c311fc49373579eb39b58b2f320\``);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` CHANGE \`departmentId\` \`departmentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` CHANGE \`serviceId\` \`serviceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`service\` DROP FOREIGN KEY \`FK_4ea0bb0b22e0fbee8449e13a897\``);
        await queryRunner.query(`ALTER TABLE \`service\` DROP COLUMN \`time_handle\``);
        await queryRunner.query(`ALTER TABLE \`service\` ADD \`time_handle\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`service\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`service\` CHANGE \`departmentId\` \`departmentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_form_service\` DROP FOREIGN KEY \`FK_1c576fe36bf8a92de40f8a41862\``);
        await queryRunner.query(`ALTER TABLE \`attribute_form_service\` CHANGE \`serviceId\` \`serviceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` DROP FOREIGN KEY \`FK_98a2967d8b070d283b464200151\``);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` DROP FOREIGN KEY \`FK_f23d86ebd6d26e00b50a83e4fd4\``);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` CHANGE \`documentId\` \`documentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` CHANGE \`attributeFormServiceId\` \`attributeFormServiceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`document\` DROP FOREIGN KEY \`FK_bb4877b43fee4ddae558cd9037a\``);
        await queryRunner.query(`ALTER TABLE \`document\` DROP FOREIGN KEY \`FK_d75a7f2b436ae997168db2b31bf\``);
        await queryRunner.query(`ALTER TABLE \`document\` DROP FOREIGN KEY \`FK_f5e5f9874c2c69b3ecbb6332b5e\``);
        await queryRunner.query(`ALTER TABLE \`document\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`document\` CHANGE \`address\` \`address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`document\` CHANGE \`departmentId\` \`departmentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`document\` CHANGE \`serviceId\` \`serviceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`document\` CHANGE \`proceduralStepId\` \`proceduralStepId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`post_comment\` DROP FOREIGN KEY \`FK_c7fb3b0d1192f17f7649062f672\``);
        await queryRunner.query(`ALTER TABLE \`post_comment\` CHANGE \`parent_id\` \`parent_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`post_comment\` CHANGE \`content\` \`content\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`post_comment\` CHANGE \`media_content\` \`media_content\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`post_comment\` CHANGE \`postId\` \`postId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`post_media_content\` DROP FOREIGN KEY \`FK_aaea8f6b6b6fe037df5846211fa\``);
        await queryRunner.query(`ALTER TABLE \`post_media_content\` CHANGE \`postId\` \`postId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`post_reaction\` DROP FOREIGN KEY \`FK_5e7b98f3cea583c73a0bbbe0de1\``);
        await queryRunner.query(`ALTER TABLE \`post_reaction\` CHANGE \`postId\` \`postId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`post\` DROP FOREIGN KEY \`FK_c91b8eb1dc23fd5dae700265ed2\``);
        await queryRunner.query(`ALTER TABLE \`post\` CHANGE \`departmentId\` \`departmentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`officer\` DROP FOREIGN KEY \`FK_23e73cad42caf33d2b38e968e4c\``);
        await queryRunner.query(`ALTER TABLE \`officer\` CHANGE \`departmentId\` \`departmentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_848c0779e2423d52fd964bbb793\` FOREIGN KEY (\`facultyId\`) REFERENCES \`faculties\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_form_enum\` ADD CONSTRAINT \`FK_db6f5036fca0a8ff7b66e43d85a\` FOREIGN KEY (\`attributeFormServiceId\`) REFERENCES \`attribute_form_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`form_file\` ADD CONSTRAINT \`FK_c9a74fea77723723f94869bf692\` FOREIGN KEY (\`serviceId\`) REFERENCES \`service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`form_file\` ADD CONSTRAINT \`FK_61b3ede9e53a3e0293518cc8dbc\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` ADD CONSTRAINT \`FK_da748edb0d12d7b468002ef37f6\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` ADD CONSTRAINT \`FK_c311fc49373579eb39b58b2f320\` FOREIGN KEY (\`serviceId\`) REFERENCES \`service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service\` ADD CONSTRAINT \`FK_4ea0bb0b22e0fbee8449e13a897\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_form_service\` ADD CONSTRAINT \`FK_1c576fe36bf8a92de40f8a41862\` FOREIGN KEY (\`serviceId\`) REFERENCES \`service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` ADD CONSTRAINT \`FK_98a2967d8b070d283b464200151\` FOREIGN KEY (\`documentId\`) REFERENCES \`document\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` ADD CONSTRAINT \`FK_f23d86ebd6d26e00b50a83e4fd4\` FOREIGN KEY (\`attributeFormServiceId\`) REFERENCES \`attribute_form_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document\` ADD CONSTRAINT \`FK_bb4877b43fee4ddae558cd9037a\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document\` ADD CONSTRAINT \`FK_d75a7f2b436ae997168db2b31bf\` FOREIGN KEY (\`serviceId\`) REFERENCES \`service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document\` ADD CONSTRAINT \`FK_f5e5f9874c2c69b3ecbb6332b5e\` FOREIGN KEY (\`proceduralStepId\`) REFERENCES \`procedural_step\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_comment\` ADD CONSTRAINT \`FK_c7fb3b0d1192f17f7649062f672\` FOREIGN KEY (\`postId\`) REFERENCES \`post\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_media_content\` ADD CONSTRAINT \`FK_aaea8f6b6b6fe037df5846211fa\` FOREIGN KEY (\`postId\`) REFERENCES \`post\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_reaction\` ADD CONSTRAINT \`FK_5e7b98f3cea583c73a0bbbe0de1\` FOREIGN KEY (\`postId\`) REFERENCES \`post\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post\` ADD CONSTRAINT \`FK_c91b8eb1dc23fd5dae700265ed2\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`officer\` ADD CONSTRAINT \`FK_23e73cad42caf33d2b38e968e4c\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`officer_roles_role\` ADD CONSTRAINT \`FK_1d723096d5579f576d8269deba8\` FOREIGN KEY (\`officerId\`) REFERENCES \`officer\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`officer_roles_role\` ADD CONSTRAINT \`FK_8cba317f8029863fb8ced755173\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`officer_roles_role\` DROP FOREIGN KEY \`FK_8cba317f8029863fb8ced755173\``);
        await queryRunner.query(`ALTER TABLE \`officer_roles_role\` DROP FOREIGN KEY \`FK_1d723096d5579f576d8269deba8\``);
        await queryRunner.query(`ALTER TABLE \`officer\` DROP FOREIGN KEY \`FK_23e73cad42caf33d2b38e968e4c\``);
        await queryRunner.query(`ALTER TABLE \`post\` DROP FOREIGN KEY \`FK_c91b8eb1dc23fd5dae700265ed2\``);
        await queryRunner.query(`ALTER TABLE \`post_reaction\` DROP FOREIGN KEY \`FK_5e7b98f3cea583c73a0bbbe0de1\``);
        await queryRunner.query(`ALTER TABLE \`post_media_content\` DROP FOREIGN KEY \`FK_aaea8f6b6b6fe037df5846211fa\``);
        await queryRunner.query(`ALTER TABLE \`post_comment\` DROP FOREIGN KEY \`FK_c7fb3b0d1192f17f7649062f672\``);
        await queryRunner.query(`ALTER TABLE \`document\` DROP FOREIGN KEY \`FK_f5e5f9874c2c69b3ecbb6332b5e\``);
        await queryRunner.query(`ALTER TABLE \`document\` DROP FOREIGN KEY \`FK_d75a7f2b436ae997168db2b31bf\``);
        await queryRunner.query(`ALTER TABLE \`document\` DROP FOREIGN KEY \`FK_bb4877b43fee4ddae558cd9037a\``);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` DROP FOREIGN KEY \`FK_f23d86ebd6d26e00b50a83e4fd4\``);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` DROP FOREIGN KEY \`FK_98a2967d8b070d283b464200151\``);
        await queryRunner.query(`ALTER TABLE \`attribute_form_service\` DROP FOREIGN KEY \`FK_1c576fe36bf8a92de40f8a41862\``);
        await queryRunner.query(`ALTER TABLE \`service\` DROP FOREIGN KEY \`FK_4ea0bb0b22e0fbee8449e13a897\``);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` DROP FOREIGN KEY \`FK_c311fc49373579eb39b58b2f320\``);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` DROP FOREIGN KEY \`FK_da748edb0d12d7b468002ef37f6\``);
        await queryRunner.query(`ALTER TABLE \`form_file\` DROP FOREIGN KEY \`FK_61b3ede9e53a3e0293518cc8dbc\``);
        await queryRunner.query(`ALTER TABLE \`form_file\` DROP FOREIGN KEY \`FK_c9a74fea77723723f94869bf692\``);
        await queryRunner.query(`ALTER TABLE \`attribute_form_enum\` DROP FOREIGN KEY \`FK_db6f5036fca0a8ff7b66e43d85a\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_848c0779e2423d52fd964bbb793\``);
        await queryRunner.query(`ALTER TABLE \`officer\` CHANGE \`departmentId\` \`departmentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`officer\` ADD CONSTRAINT \`FK_23e73cad42caf33d2b38e968e4c\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post\` CHANGE \`departmentId\` \`departmentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`post\` ADD CONSTRAINT \`FK_c91b8eb1dc23fd5dae700265ed2\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_reaction\` CHANGE \`postId\` \`postId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`post_reaction\` ADD CONSTRAINT \`FK_5e7b98f3cea583c73a0bbbe0de1\` FOREIGN KEY (\`postId\`) REFERENCES \`post\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_media_content\` CHANGE \`postId\` \`postId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`post_media_content\` ADD CONSTRAINT \`FK_aaea8f6b6b6fe037df5846211fa\` FOREIGN KEY (\`postId\`) REFERENCES \`post\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_comment\` CHANGE \`postId\` \`postId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`post_comment\` CHANGE \`media_content\` \`media_content\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`post_comment\` CHANGE \`content\` \`content\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`post_comment\` CHANGE \`parent_id\` \`parent_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`post_comment\` ADD CONSTRAINT \`FK_c7fb3b0d1192f17f7649062f672\` FOREIGN KEY (\`postId\`) REFERENCES \`post\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document\` CHANGE \`proceduralStepId\` \`proceduralStepId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document\` CHANGE \`serviceId\` \`serviceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document\` CHANGE \`departmentId\` \`departmentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document\` CHANGE \`address\` \`address\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document\` ADD CONSTRAINT \`FK_f5e5f9874c2c69b3ecbb6332b5e\` FOREIGN KEY (\`proceduralStepId\`) REFERENCES \`procedural_step\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document\` ADD CONSTRAINT \`FK_d75a7f2b436ae997168db2b31bf\` FOREIGN KEY (\`serviceId\`) REFERENCES \`service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document\` ADD CONSTRAINT \`FK_bb4877b43fee4ddae558cd9037a\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` CHANGE \`attributeFormServiceId\` \`attributeFormServiceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` CHANGE \`documentId\` \`documentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` ADD CONSTRAINT \`FK_f23d86ebd6d26e00b50a83e4fd4\` FOREIGN KEY (\`attributeFormServiceId\`) REFERENCES \`attribute_form_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_value\` ADD CONSTRAINT \`FK_98a2967d8b070d283b464200151\` FOREIGN KEY (\`documentId\`) REFERENCES \`document\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_form_service\` CHANGE \`serviceId\` \`serviceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_form_service\` ADD CONSTRAINT \`FK_1c576fe36bf8a92de40f8a41862\` FOREIGN KEY (\`serviceId\`) REFERENCES \`service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service\` CHANGE \`departmentId\` \`departmentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`service\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`service\` DROP COLUMN \`time_handle\``);
        await queryRunner.query(`ALTER TABLE \`service\` ADD \`time_handle\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`service\` ADD CONSTRAINT \`FK_4ea0bb0b22e0fbee8449e13a897\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` CHANGE \`serviceId\` \`serviceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` CHANGE \`departmentId\` \`departmentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` ADD CONSTRAINT \`FK_c311fc49373579eb39b58b2f320\` FOREIGN KEY (\`serviceId\`) REFERENCES \`service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`procedural_step\` ADD CONSTRAINT \`FK_da748edb0d12d7b468002ef37f6\` FOREIGN KEY (\`departmentId\`) REFERENCES \`department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_form_enum\` CHANGE \`attributeFormServiceId\` \`attributeFormServiceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_form_enum\` ADD CONSTRAINT \`FK_db6f5036fca0a8ff7b66e43d85a\` FOREIGN KEY (\`attributeFormServiceId\`) REFERENCES \`attribute_form_service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`nav_menu\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`parent_id\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`icon\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`routerLink\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`label\``);
        await queryRunner.query(`ALTER TABLE \`officer\` DROP COLUMN \`avatar\``);
        await queryRunner.query(`ALTER TABLE \`officer\` DROP COLUMN \`gender\``);
        await queryRunner.query(`ALTER TABLE \`officer\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`officer\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`facultyId\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`avatar\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`gender\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`in_class\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_8cba317f8029863fb8ced75517\` ON \`officer_roles_role\``);
        await queryRunner.query(`DROP INDEX \`IDX_1d723096d5579f576d8269deba\` ON \`officer_roles_role\``);
        await queryRunner.query(`DROP TABLE \`officer_roles_role\``);
        await queryRunner.query(`DROP TABLE \`form_file\``);
        await queryRunner.query(`DROP TABLE \`faculties\``);
    }

}
